export const myTheme = {
  direction: {
    row: 'row',
    rowReverse: 'row-reverse',
    column: 'column',
    columnReverse: 'column-reverse',
  },
  align: {
    auto: 'auto',
    normal: 'normal',
    stretch: 'stretch',
    center: 'center',
    start: 'start',
    end: 'end',
    flexStart: 'flex-start',
    flexEnd: 'flex-end',
    selfStart: 'self-start',
    selfEnd: 'self-end',
    left: 'left',
    right: 'right',
    baseline: 'baseline',
    firstBaseline: 'first baseline',
    lastBaseline: 'last baseline',
    safeCenter: 'safe center',
    unsafeCenter: 'unsafe center',
    inherit: 'inherit',
    initial: 'initial',
    revert: 'revert',
    revertLayer: 'revert-layer',
    unset: 'unset',
  },
  alignContent: {
    flexStart: 'flex-start',
    flexEnd: 'flex-end',
    center: 'center',
    stretch: 'stretch',
    spaceBetween: 'spaceBetween',
    spaceAround: 'spaceAround',
  },
  flexWrap: {
    wrap: 'wrap',
    nowrap: 'nowrap',
  },
  position: {
    absolute: 'absolute',
    relative: 'relative',
    fixed: 'fixed',
    sticky: 'sticky',
    static: 'static',
    initial: 'initial',
  },
  justify: {
    flexStart: 'flex-start',
    flexEnd: 'flex-end',
    center: 'center',
    spaceBetween: 'space-between',
    spaceAround: 'space-around',
    spaceEvenly: 'space-evenly',
  },
  colors: {
    primary: {
      light: '#8eee70',
      medium: '#44A625',
      mediumAlt: '#a5e990',
      dark: '#0F6E02',
      none: 'transparent',
    },
    secondary: {
      light: '#E6F3DD',
      medium: '#B2DE9A',
      mediumAlt: '#B2DE9A',
      dark: '#8BB673',
      none: 'transparent',
    },
    accent: {
      light: '#B0CAFA',
      medium: '#9AB2DE',
      mediumAlt: '#9AB2DE',
      dark: '#7386A9',
      none: 'transparent',
    },
    error: {
      light: '#FF5050',
      medium: '#D63636',
      mediumAlt: '#D63636',
      dark: '#BA2B2B',
      none: 'transparent',
    },
    warning: {
      light: '#f9c453',
      medium: '#F8B01E',
      mediumAlt: '#F8B01E',
      dark: '#f7a708',
      none: 'transparent',
    },
    info: {
      light: '#FFA3C3',
      medium: '#DE9AB2',
      mediumAlt: '#DE9AB2',
      dark: '#C8869D',
      none: 'transparent',
    },
    success: {
      light: '#8aee6b',
      medium: '#00B968',
      mediumAlt: '#00B968',
      dark: '#01A45C',
      none: 'transparent',
    },
    background: {
      light: '#1b1b1b',
      medium: '#1a1a1a',
      mediumAlt: '#1a1a1a',
      dark: '#edebeb',
      none: 'transparent',
    },
    foreground: {
      light: '#313131',
      medium: '#D9D9D9',
      mediumAlt: '#D9D9D9',
      dark: '#181818',
      none: 'transparent',
    },
    text: {
      light: '#fbfbfb',
      medium: '#F2F2F2',
      mediumAlt: '#F2F2F2',
      dark: '#EEEDF2',
      none: 'transparent',
    },
    textAlt: {
      light: '#A7B69E',
      medium: '#586153',
      mediumAlt: '#586153',
      dark: '#3D413A',
      none: 'transparent',
    },
  },
  dimensions: {
    tight: '25%',
    small: '33.33%',
    medium: '50%',
    large: '100%',
    auto: 'auto',
    minContent: 'min-content',
    maxContent: 'max-content',
    fitContent: 'fit-content',
  },
  spacing: {
    none: 0,
    xTight: 0.5,
    tight: 1,
    snug: 1.2,
    regular: 1.5,
    loose: 2,
    xLoose: 3,
  },
  borderRadius: {
    none: 0,
    xSmall: 5,
    small: 7,
    regular: 12,
    large: 20,
    full: 1000,
  },
  shadows: {
    none: 'none',
    small: '0.1rem 0.1rem 0.5rem rgba(0, 0, 0, 0.1)',
    xSmall: 'rgb(201 201 201 / 50%) 1px 1px 10px',
    medium: '3px 5px 9px rgba(0, 0, 0, 0.1)',
    large: '5px 8px 15px rgba(0, 0, 0, 0.15)',
  },
  font: {
    family: {
      primary: "'Jost', 'Roboto', 'sans-serif'",
      secondary: "'Poppins', 'Roboto', 'sans-serif'",
    },
    sizes: {
      none: 0,
      xSmall: 12,
      small: 14,
      xMedium: 18,
      medium: 20,
      large: 25,
      xLarge: 31,
      xxLarge: 51,
      xxxLarge: 64,
    },
    weights: {
      light: 300,
      regular: 400,
      medium: 500,
      bold: 600,
      xBold: 700,
    },
  },
  textAlign: {
    left: 'left',
    right: 'right',
    center: 'center',
    justify: 'justify',
    initial: 'initial',
    inherit: 'inherit',
  },
  zIndex: {
    none: 0,
    xTight: 5,
    tight: 10,
    snug: 15,
    regular: 20,
    loose: 25,
    xLoose: 30,
  },
  justifySelf: {
    auto: 'auto',
    normal: 'normal',
    stretch: 'stretch',
    center: 'center',
    start: 'start',
    end: 'end',
    flexStart: 'flex-start',
    flexEnd: 'flex-end',
    selfStart: 'self-start',
    selfEnd: 'self-end',
    left: 'left',
    right: 'right',
    baseline: 'baseline',
    firstBaseline: 'first baseline',
    lastBaseline: 'last baseline',
    safeCenter: 'safe center',
    unsafeCenter: 'unsafe center',
    inherit: 'inherit',
    initial: 'initial',
    revert: 'revert',
    revertLayer: 'revert-layer',
    unset: 'unset',
  },
  overflow: {
    visible: 'visible',
    hidden: 'hidden',
    clip: 'clip',
    scroll: 'scroll',
    auto: 'auto',
    initial: 'initial',
    inherit: 'inherit',
    unset: 'unset',
  },
  alignSelf: {
    auto: 'auto',
    normal: 'normal',
    stretch: 'stretch',
    center: 'center',
    start: 'start',
    end: 'end',
    flexStart: 'flex-start',
    flexEnd: 'flex-end',
    selfStart: 'self-start',
    selfEnd: 'self-end',
    left: 'left',
    right: 'right',
    baseline: 'baseline',
    firstBaseline: 'first baseline',
    lastBaseline: 'last baseline',
    safeCenter: 'safe center',
    unsafeCenter: 'unsafe center',
    inherit: 'inherit',
    initial: 'initial',
    revert: 'revert',
    revertLayer: 'revert-layer',
    unset: 'unset',
  },
} as const;
